### ISSUE TITLE
타이핑 페이지 기능

### ISSUE THREAD

**Issue by ricky0813** [ty-ing/ty-ing_FE#4]
- [x]  타이틀 모달 구현
- [x] 시간멈췄다 동작할 때 잘 작동하게 하기
- [x] 줄바꿈시 고장나는 문제 해결
- [x] 문단 및 줄바꿈 부분 반응형 고려하기
- [x] 영어로만 타이핑 되도록 하기
- [x] 포커스 아웃 시 단어 클릭되지 않게 하기
- [x] 타이핑 완료 시 인증서 모달기능 구현
- [x] 한 문단이상 타이핑 시 버튼 클릭으로 인증서 모달 띄우기

**Comment by hyejin4169** [comment]
Done
